# Tugas Besar: Face Recognition dengan Keras


### Instruksi Tugas Besar
Didalam notebook ini, beberapa script sudah disediakan sehingga Anda hanya akan mengerjakan beberapa bagian script yang kosong. Selama pengerjaan Anda akan diberi petunjuk terkait alur dan instruksi pengerjaan. Oleh karena itu, perhatikan istruksi dengan baik. Tulisan `Tugas:` mengindikasikan script kosong yang harus Anda kerjakan agar keseluruhan sistem dapat berjalan dengan baik. 

>**Note:** Setelah Anda menyelesaikan tugas besar ini, Anda diminta untuk mengumpulkan tugas besar ini dalam bentuk HTML. Sebelum diubah menjadi HTML, semua script harus dipastikan sudah di-run agar penilai dapat melihat hasil dari kode yang dijalankan. Anda dapat mengubah notebook ini menjadi HTML dengan **File -> Download as -> HTML(.html)**. Sertakan file HTML tersebut bersama folder tugas besar ini.

Selain mengimplementasikan bagian script yang kosong, Anda juga diminta menjawab pertanyaan analisis. Pertanyaan tersebut ditandai dengan tulisan **'Pertanyaan X'**. Baca dengan baik pertanyaan tersebut dan berikan jawaban anda secara jelas di bagian dengan tulisan **Jawaban**. Tugas besar Anda akan dinilai berdasarkan kode implementasi dan juga jawaban analisis setiap pertanyaan.

>**Note:** Sel Code dan Markdown dapat dieksekusi dengan **Shift+Enter** di keyboard. Sel Markdown dapat di-edit dengan mengklik dua kali sel tersebut.

Bagian yang diberi tanda **_opsional_** merupakan tugas yang diberikan jika Anda ingin mendapatkan nilai lebih dari standar minimum.

### Alur Tugas Besar
Notebook tugas besar ini dibagi menjadi beberapa langkah sebagai berikut. Silahkan diperhatikan dan dipahami alur dan detail setiap langkah.
1. Loading Dataset
2. Periksa Isi Dataset
3. Pisah Fitur dan Label
4. Olah data label dengan One-Hot-Encoding
5. Definisikan Model Machine Learning
6. Definisikan Hyperparameters
7. Definisikan Optimizer dan Loss Function
8. Training Model
9. Evaluasi Model
10. Eksperimen Model Machine Learning Lain(Opsional)
11. Implementasi Model

## Kelompok yang mengerjakan
Silahkan klik dua kali sel ini kemudian isi bagian yang kosong.

**Kelompok:** (isi no kelompok)

**Anggota Kelompok:**
1. anggota 1 | NIM 1
2. anggota 2 | NIM 2
3. anggota 3 | NIM 3


### Persiapkan library yang dibutuhkan
Tugas besar ini menggunakan banyak library yang bisa dilihat di file requirements.txt. Script dibawah dapat dijalankan untuk instalasi semua library tersebut.

In [0]:
!python3 -m pip install -r requirements.txt

## 1. Loading Dataset
Dataset yang digunakan dalam tugas besar ini disimpan dalam file CSV dengan nama train.csv dan test.csv. Berikut adalah script yang digunakan untuk membaca dataset CSV tersebut yang kemudian disimpan dalam dataframe Pandas.

In [0]:
import pandas as pd

## Direktori dataset
dir_trainset = "./dataset/trainset.csv"  # Dataset for Training 
dir_validset = "./dataset/validset.csv"  # Dataset for Validation 
dir_testset = "./dataset/testset.csv"    # Dataset for Testing

## Membaca data csv ke Dataframe Pandas
train_pd = pd.read_csv(dir_trainset, index_col=0)
valid_pd = pd.read_csv(dir_validset, index_col=0)
test_pd = pd.read_csv(dir_testset, index_col=0)

## proses membaca dataset membutuhkan waktu yang cukup lama sekitar 1-2 menit

print('trainset, validset & testset berhasil dibaca!')

trainset dan testset berhasil dibaca!


## 2. Periksa Isi Dataset
Dataset ini merupakan representasi dari foto-foto wajah yang nantinya akan diklasifikasikan dengan model machine learning. Setiap foto wajah direpresentasikan dalam 512 fitur muka yang biasanya dikenal dengan istilah **feature embeddings**. Script dibawah ini memperlihatkan isi dataset untuk 10 baris pertama. Perhatikan bahwa terdapat informasi 512 fitur wajah pada kolom `feature-0` hingga `feature-511` beserta ID wajahnya pada kolom `face_id`. Fitur-fitur wajah tersebut diperoleh dengan Convolutional Neural Network(CNN) yang dapat dilihat pada skema dibawah ini. Karena CNN bukan merupakan bahasan utama dalam mata kuliah Dasar Sistem Kendali Cerdas maka facenet tidak dibahas lebih lanjut pada tugas besar ini. Namun, mahasiswa diperbolehkan untuk mempelajari beberapa contoh CNN yang digunakan untuk ekstrak feature embeddings tersebut, seperti [ageitgey](https://github.com/ageitgey/face_recognition) dan [davidsandberg](https://github.com/davidsandberg/facenet).
<img src="files/assets/feature_embeddings.PNG">

In [0]:
## Lihat isi dataset
train_pd[:10]

feature-0  feature-1  feature-2  feature-3  feature-4  feature-5  \
0   0.249508   0.140941   0.019358   0.069558   0.178254  -0.050526   
1   0.216727   0.186541   0.050070   0.098276   0.140091  -0.080892   
2   0.218126   0.180674   0.037945   0.061499   0.153078  -0.084201   
3   0.211576   0.184971   0.055630   0.090802   0.131649  -0.078810   
4   0.245235   0.161489   0.022288   0.038239   0.167697  -0.075540   
5   0.257464   0.158202   0.015021   0.033080   0.183314  -0.040514   
6   0.184529   0.117506   0.069546   0.077402   0.130801  -0.092427   
7   0.224221   0.188585   0.060175   0.083710   0.106269  -0.115096   
8   0.202705   0.173892   0.061936   0.078606   0.150277  -0.079902   
9   0.223490   0.176232   0.034974   0.073048   0.145010  -0.073925   

   feature-6  feature-7  feature-8  feature-9    ...      feature-119  \
0   0.116203   0.085332  -0.034444   0.098884    ...         0.009328   
1   0.087637   0.044271  -0.098830   0.055600    ...         0.005635   
2   0.082621   0.056989  -0.074941   0.036297    ...         0.015347   
3   0.091326   0.051762  -0.104256   0.051484    ...         0.008539   
4   0.061712   0.055288  -0.072449   0.058405    ...         0.028506   
5   0.080250   0.062811  -0.049371   0.092126    ...         0.006336   
6   0.006699   0.019700  -0.203980   0.030491    ...         0.079844   
7   0.030030   0.081728  -0.080314   0.066757    ...         0.021116   
8   0.071888   0.063126  -0.086653   0.063259    ...         0.014427   
9   0.079842   0.068924  -0.101150   0.078057    ...         0.039560   

   feature-120  feature-121  feature-122  feature-123  feature-124  \
0     0.100447     0.128663    -0.037708     0.003169     0.065096   
1     0.147227     0.120921    -0.075316    -0.024081     0.081287   
2     0.123694     0.116205    -0.080593    -0.018862     0.071693   
3     0.157163     0.126885    -0.082595    -0.015439     0.087266   
4     0.096711     0.122548    -0.060332    -0.041631     0.068309   
5     0.115924     0.116511    -0.055674    -0.027272     0.043640   
6     0.107520     0.119651    -0.046843    -0.020426     0.020199   
7     0.138170     0.176310    -0.097431    -0.017925     0.077682   
8     0.138062     0.114148    -0.084530    -0.032800     0.075365   
9     0.121001     0.131677    -0.083940    -0.046745     0.062902   

   feature-125  feature-126  feature-127  person_id  
0    -0.023164     0.011312    -0.008885          1  
1     0.031427     0.015923    -0.006036          1  
2     0.019164    -0.049722    -0.035844          1  
3     0.028905    -0.002334     0.002757          1  
4     0.053039    -0.068629    -0.032705          1  
5     0.059178    -0.031775     0.012397          1  
6     0.048499    -0.042398    -0.019206          1  
7     0.065853    -0.043213     0.032218          1  
8     0.050272    -0.066085    -0.014293          1  
9     0.045239    -0.054479    -0.021212          1  

[10 rows x 129 columns]

## 3. Pisahkan Fitur dan Label
Sebelum dataset dapat digunakan dalam training, validation dan testing machine learning, perlu dilakukan pemisahan antara fitur dan label untuk masing-masing trainingset, validationset dan testset. Dalam hal ini, fitur merupakan 512 fitur wajah yang terdapat pada kolom nol hingga 511 `feature-0`-`feature-511`, sedangkan label merupakan kolom ke 512 `face_id`. Namun, perlu diketahui bahwa Keras menerima data dalam bentuk _numpy ndarray_ bukan _pandas dataframe_ sedangkan dataset kita sebelumnya dalam bentuk _pandas dataframe_. Oleh karena itu, perlu dilakukan konversi data dari pandas ke numpy dengan [pandas.dataframe.values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html).

Dengan demikian berikut adalah langkah-langkah yang perlu dilakukan:
1. Acak baris yang ada didalam dataset _pandas dataframe_ masing-masing `train_pd`, `valid_pd` dan `test_pd` dengan [sklearn.utils.shuffle](https://scikit-learn.org/stable/modules/generated/sklearn.utils.shuffle.html) dengan contoh sebagai berikut [shuffle-dataframe-rows](https://stackoverflow.com/questions/29576430/shuffle-dataframe-rows)
2. Konversi data dari _pandas dataframe_ menjadi _numpy ndarray_.
3. Pisah data fitur yang disimpan dalam `X_train`, `X_val` dan `X_test` dengan [numpy indexing](https://www.numpy.org/devdocs/user/basics.indexing.html).
4. Pisah data label `y_train`, `y_val` dan `y_test`. Namun, perlu diketahui bahwa dimensi vektor harus dalam bentuk vektor kolom yang dapat dilakukan dengan [numpy.ndarray.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html)

In [0]:
from sklearn.utils import shuffle

## Tugas : Acak baris train_pd dan test_pd
train_pd = None
valid_pd = None
test_pd = None

In [0]:
import numpy as np

## Tugas : Konversi dataframe pandas ke numpy ndarray
train = train_pd.values
print('trainingset')
print(train[:5,:5]) # Tampilkan 5 kolom pertama dan 5 baris pertama

valid = valid_pd.values
print('\nvalidset')
print(valid[:5,:5])

test = test_pd.values
print('\ntestset')
print(test[:5,:5])

trainingset
[[ 0.1556045   0.09190694 -0.05697304  0.10078716  0.11692164]
 [ 0.11699945  0.05099101 -0.12017793  0.0141609  -0.02929075]
 [ 0.09789222  0.05472619  0.02016508  0.14047895  0.08256042]
 [ 0.12601298  0.05530059  0.05999723  0.02195709  0.02276796]
 [ 0.07944823  0.07345875  0.0080224  -0.05783851 -0.01005457]]

testset
[[ 0.02127057  0.05560327 -0.09081914  0.03807011 -0.05890091]
 [ 0.10710452  0.15742023  0.05348891  0.00598381  0.00628382]
 [ 0.15290627 -0.06366513  0.03544303  0.06766491  0.11990856]
 [ 0.14007363  0.09067726  0.01565232  0.01997773  0.02389572]
 [ 0.16874114  0.08379415  0.04513727  0.11792881  0.02879788]]


In [0]:
## Tugas : Pisah data fitur dan data label

# Trainingset
X_train = train[:,:512]
y_train = train[:,512].reshape(X_train.shape[0],-1)
print('Dimensi matriks trainset')
print('fitur: '+ str(X_train.shape))
print('label: '+ str(y_train.shape))

# Validset
X_valid = valid[:,:512]
y_valid = valid[:,512].reshape(X_valid.shape[0],-1)
print('\nDimensi matriks validset')
print('fitur: '+ str(X_valid.shape))
print('label: '+ str(y_valid.shape))

# Testset
X_test = test[:,:512]
y_test = test[:,512].reshape(X_test.shape[0],-1)
print('\nDimensi matriks testset')
print('fitur: '+ str(X_test.shape))
print('label: '+ str(y_test.shape))

## Hasil Seharusnya di console
##
##   Dimensi matriks trainset
##   fitur: (16700, 512)
##   label: (16700, 1)
##   
##   Dimensi matriks validset
##   fitur: (1161, 512)
##   label: (1161, 1)
##   
##   Dimensi matriks testset
##   fitur: (1200, 512)
##   label: (1200, 1)

Dimensi matriks trainset
fitur: (36224, 128)
label: (36224, 1)

Dimensi matriks testset
fitur: (5534, 128)
label: (5534, 1)


## 4. Olah data label dengan One-Hot-Encoding
Data label dalam `y_train` dan `y_test` masih berupa tipe integer dimana satu nilai merepresentasikan satu identitas wajah. Dalam keras, data label perlu diolah menjadi matriks yang tiap baris berupa vektor nilai nol atau satu. Data label tersebut perlu dioleh dengan metode [One-Hot-Encoding](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f).

Misalkan terdapat 3 kelas dan data label adalah sebagai berikut 

[[0], 
 [1], 
 [1], 
 [2]].

Dengan metode one-hot-encoding maka data label akan menjadi

[[1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1]]
 
Salah satu cara mengimplementasikan one-hot encoding adalah dengan menggunakan library [sklearn.preprocessing.LabelBinazer()](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html).

*NB:* Perhatikan bahwa jumlah label y_train, y_valid & y_test berbeda yang bisa menyebabkan potensi kesalahan pada one-hot encoding tanpa modifikasi!!

In [0]:
from sklearn import preprocessing

## Tugas : Olah data label dengan metode one-hot encoding

y_train = None # Label untuk traningset
y_valid = None # Label untuk validset
y_test = None # Label untuk testset

print('Dimensi label setelah one-hot-encoding')
print('train: ' + str(y_train.shape))
print('valid: ' + str(y_valid.shape))
print('test : ' + str(y_test.shape))

## Hasil Seharusnya di console
##  
##  Dimensi label setelah one-hot-encoding
##  train: (38781, 200)
##  valid: (2368, 200)
##  test : (2458, 200)

Dimensi label setelah one-hot-encoding
train: (36224, 153)
test : (5534, 153)


## 5. Definisikan Model Machine Learning
Pada tugas besar ini, Anda diharapkan membangun model Neural Network dengan Keras yang dapat dilihat contoh implementasinya pada [API Sequential Keras](https://keras.io/getting-started/sequential-model-guide/). Silahkan bereksperimen dengan jumlah hidden layer, jumlah node dan fungsi aktivasi. Selain itu, silahkan gunakan Dropout sebagai salah satu metode penanganan overfitting.

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

## Tugas : Definisikan Parameter Model
dimensi_input = None  # Dimensi data input (jumlah fitur)
hidden_layer_1 = None # Jumlah node pada hidden layer pertama
hidden_layer_2 = None # Jumlah node pada hidden layer kedua
output_layer = None    # Jumlah node pada output layer
drop_prob = None      # Nilai probability untuk dropout layer

## Tugas : Definisikan model dibawah
## Coba model machine learning

## Tampilkan definisi model
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 512)               66048     
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_4 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 153)               78489     
Total params: 407,193
Trainable params: 407,193
Non-trainable params: 0
_________________________________________________________________


## 6. Definisikan Hyperparameters
Hyperparameters merupakan nilai-nilai yang perlu ditentukan agar kita dapat memeroleh hasil training yang baik. Dalam hal ini, perlu ditentukan nilai learning rate, ukuran batch dan jumlah iterasi epoch.

In [0]:
## Tugas : Tentukan Nilai Hyperparameters
learning_rate = None
batch_size = None
epoch = None

## 7. Definisikan Optimizer dan Loss Function
Optimizer merupakan opsi yang juga perlu diperhatikan, pilihan optimizer dalam Keras dapat dilihat [keras-optimizers](https://keras.io/optimizers/). Selain itu, loss function juga perlu dipilih yang disesuaikan dengan jenis data yang digunakan. Dalam Keras jenis-jenis loss function dapat dilihat di [keras-losses](https://keras.io/losses/).

In [0]:
from keras.optimizers import Adam

## Tugas : Definisikan Optimizer dan Loss function

optimizer = None

model.compile(loss= None , optimizer= None , metrics=[ 'accuracy' ])

## 8. Training Model
Model dapat di-train dengan script sebagai berikut. Perlu diperhatikan bahwa training machine learning biasanya dilakukan berulang kali dengan mengatur hyperparameter model(hidden layer, jumlah node, dll) dan hyperparameter training (learning rate, ukuran batch, optimizer, dll) sehingga diperoleh model hasil training dengan akurasi terbaik. Tidak terdapat rumus baku tentang nilai hyperparameter untuk menghasilkan training terbaik. Akan tetapi, terdapat beberapa artikel yang menjelaskan tentang sense dalam memilih hyperparameter sebagai berikut [Neural Networks and Deep Learning book - Chapter 3: How to choose a neural network's hyper-parameters? by Michael Nielsen](http://neuralnetworksanddeeplearning.com/chap3.html#how_to_choose_a_neural_network's_hyper-parameters) dan [Deep Learning book - chapter 11.4: Selecting Hyperparameters by Ian Goodfellow, Yoshua Bengio, Aaron Courville](http://www.deeplearningbook.org/contents/guidelines.html)

In [0]:
## Train Model dengan script dibawah
model.fit()

Epoch 1/10
36224/36224 [==============================] - 6s 157us/step - loss: 3.6468 - acc: 0.2804
Epoch 2/10
36224/36224 [==============================] - 5s 143us/step - loss: 0.7136 - acc: 0.8509
Epoch 3/10
36224/36224 [==============================] - 5s 145us/step - loss: 0.2606 - acc: 0.9441
Epoch 4/10
36224/36224 [==============================] - 5s 144us/step - loss: 0.1631 - acc: 0.9629
Epoch 5/10
36224/36224 [==============================] - 5s 145us/step - loss: 0.1166 - acc: 0.9734
Epoch 6/10
36224/36224 [==============================] - 5s 145us/step - loss: 0.0884 - acc: 0.9798
Epoch 7/10
36224/36224 [==============================] - 5s 147us/step - loss: 0.0730 - acc: 0.9832
Epoch 8/10
36224/36224 [==============================] - 5s 147us/step - loss: 0.0583 - acc: 0.9871
Epoch 9/10
36224/36224 [==============================] - 5s 145us/step - loss: 0.0504 - acc: 0.9885
Epoch 10/10
36224/36224 [==============================] - 5s 147us/step - loss: 0.0419 - a

__Pertanyaan 1__: Jelaskan langkah-langkah yang Anda lakukan sehingga mendapat akurasi terbaik saat ini? Uraikan setiap langkah beserta alasannya. Menurut Anda, apakah model saat ini performanya sudah cukup?

__Jawaban__: (silahkan klik dua kali cell ini)
- langkah 1
- langkah 2
- ...


## 8. Evaluasi Model (Testing)
Berikut adalah script yang dapat digunakan untuk menguji model dengan dataset test. Jika akurasi hasil evaluasi jauh lebih kecil daripada akurasi training, maka model Anda mengalami **overfitting**.

In [0]:
## Evaluasi Model dengan script dibawah
score = model.evaluate(X_test, y_test, batch_size=128)
print('Loss test    : {:.2f}'.format(score[0]))
print('Akurasi test : {:.2f} %'.format(score[1]*100))

5534/5534 [==============================] - 0s 66us/step
Loss test    : 1.19
Akurasi test : 78.62 %


## 9. Eksperimen Model Machine Learning Lain (Opsional)
Neural Network merupakan salah satu dari banyak algoritma machine learning. Jika Anda ingin mengerjakan bagian opsional ini silahkan bereksperimen membangun face recognition dengan algoritma lain, seperti Support Vector Machine(SVM).

In [0]:
## Tugas : (Opsional)
## Membangun model face recognition dengan algoritma selain NN
## Silahkan bereksperimen dengan banyak algoritma

__Pertanyaan 2__: Apakah algoritma terbaik yang Anda gunakan lebih baik dari Neural Network? Silahkan jelaskan alasan kenapa algoritma tersebut lebih baik atau lebih buruk dari Neural Network?

__Jawaban__: (silahkan klik dua kali cell ini)
